### PR TITLE
add gyro toggle and warning

### PR DESCRIPTION
**Pull request by rubensayshi**

### CODE REVIEW

**Comment by Archaegeo** [comment]
Ruben,

We intentionally removed the gyro as it just takes up a slot and we already get pitch and roll from code.  Why do you want a gyro?

**Comment by rubensayshi** [comment]
when you enable the gyro it changes the orientation of your ship to that of the gyro instead of the core.

I've build a ship with the space engines being vertically facing, so I need to enable the gyro when I get into space so the orientation switches, otherwise nothing works :P

maybe I can remove it from the auto detect to not eat up slots by default, but leave the code so I (and maybe others) can manually link the gyro to get the toggle option?

**Comment by Archaegeo** [comment]
My remaining concern is that this kills ships with AGG.  Im going to hold off for now unless we get a lot of request to pull it into the main

**Comment by rubensayshi** [comment]
I think you misread, if there's an AGG then the ALT+G toggles the AGG, only if there's no AGG then it toggles the gyro

**Comment by Archaegeo** [comment]
Ok, will merge. its an easy  "feature" that doesnt have much impact on performance

**Comment by Archaegeo** [comment]
if gyro ~= nil then
    GyroIsOn = gyro.getState() == 1
end

this throws an error of attempted to call a nil value getState()  please investigate

Also code needs to be update to reflect new display html

**Comment by Archaegeo** [comment]
Finally hand merged in version 4.15

**Pull request closed without merging**
