### PR TITLE
Added Logrithmic Vertical Speed Indicator

### PR DESCRIPTION
**Pull request by lisa-lionheart**
Added a vertical speed indicator to the bottom left of the hud

image

### CODE REVIEW

**Comment by Dimencia** [comment]
Oh hey we love this thing btw.  We're talking about setting up a whole instrument panel to support it.
You're welcome to give us more PRs for other useful analog instruments that might go well in a panel ;)

**Comment by lisa-lionheart** [comment]
I was going to redo this since it seemed to have merge issues but its just confused by whitespace

**Comment by Archaegeo** [comment]
Ive got it integrated now, it will be coming out in 3.96, working very well
(the virtual speed indicator)

**Comment by Archaegeo** [comment]
Closing this pull request since we merged the code by hand.

**Pull request closed without merging**
